"""initial schema with users

Revision ID: 2f6734d4367e
Revises: 
Create Date: 2026-04-07 02:33:20.425806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f6734d4367e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_journals_user_id'), 'journals', ['user_id'], unique=False)
    op.add_column('positions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('positions', sa.Column('entry_volume', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('volume_50ma', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('relative_volume', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('prior_day_rel_volume', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('opening_gap_pct', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('day_movement_pct', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('day_type', sa.String(length=20), nullable=True))
    op.add_column('positions', sa.Column('atr_14', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('true_range', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('entry_pct_of_atr', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('relative_volatility', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('sma_50', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('price_vs_sma50_pct', sa.Float(), nullable=True))
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.add_column('trades', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_column('trades', 'user_id')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_column('positions', 'price_vs_sma50_pct')
    op.drop_column('positions', 'sma_50')
    op.drop_column('positions', 'relative_volatility')
    op.drop_column('positions', 'entry_pct_of_atr')
    op.drop_column('positions', 'true_range')
    op.drop_column('positions', 'atr_14')
    op.drop_column('positions', 'day_type')
    op.drop_column('positions', 'day_movement_pct')
    op.drop_column('positions', 'opening_gap_pct')
    op.drop_column('positions', 'prior_day_rel_volume')
    op.drop_column('positions', 'relative_volume')
    op.drop_column('positions', 'volume_50ma')
    op.drop_column('positions', 'entry_volume')
    op.drop_column('positions', 'user_id')
    op.drop_index(op.f('ix_journals_user_id'), table_name='journals')
    op.drop_column('journals', 'user_id')
    # ### end Alembic commands ###
